### ISSUE TITLE
🐛 Issue - local images are not displayed

### ISSUE THREAD

**Issue by AM-XR** [ebullient/obsidian-slides-extended#98]
### Issue
Local image embeds dont work at all on Win 10. Not in the preview and also not in the browser and returns the following:
`Failed to load resource: the server responded with a status of 404 (Not Found)`

### embedding synthax
different formattings i tried that worked with advanced slides:
%% Default %%
`![[Out_3.jpg|300x250]]`
 
%% Relative Path %%
`![](../_ImagesCollection/Out_3.jpg)`

weblinks do work:
`![](https://picsum.photos/id/1005/250/250)`

### steps i tried to solve issue
- reinstalling
- stopping and reenabling the extended slides server
- back and forth testing with advanced slides
- checked direct paths in browser, files are not there: http://localhost:3011/images/img_a.jpg
`{"message":"Route GET:/images/img_a.jpg not found","error":"Not Found","statusCode":404}`
- Tested on multiple Win 10 devices

### Test Vault
same isolated test vault as sent initially in discussions

### Debug Info
SYSTEM INFO:
	Obsidian version: v1.8.4
	Installer version: v1.8.3
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Language: en
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Slides Extended v2.1.8

### Log File Attached
[localhost-1738405545751.log](https://github.com/user-attachments/files/18628356/localhost-1738405545751.log)

> Navigated to http://localhost:3011/Test%20Vault%20for%20Advanced%20Slides.md
> lockdown-install.js:1 Removing unpermitted intrinsics
> controls.js:89 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
> (anonymous) @ controls.js:89
> (anonymous) @ controls.js:89
> bind @ controls.js:88
> Se @ reveal.js:571
> Je @ reveal.js:1658
> Ee @ reveal.js:554
> ye @ reveal.js:214
> controls.js:90 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
> (anonymous) @ controls.js:90
> (anonymous) @ controls.js:90
> bind @ controls.js:88
> Se @ reveal.js:571
> Je @ reveal.js:1658
> Ee @ reveal.js:554
> ye @ reveal.js:214
> controls.js:91 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
> (anonymous) @ controls.js:91
> (anonymous) @ controls.js:91
> bind @ controls.js:88
> Se @ reveal.js:571
> Je @ reveal.js:1658
> Ee @ reveal.js:554
> ye @ reveal.js:214
> controls.js:92 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
> (anonymous) @ controls.js:92
> (anonymous) @ controls.js:92
> bind @ controls.js:88
> Se @ reveal.js:571
> Je @ reveal.js:1658
> Ee @ reveal.js:554
> ye @ reveal.js:214
> img_a.jpg:1 
>         
>         
>        GET http://localhost:3011/images/img_a.jpg 404 (Not Found)
> Image
> (anonymous) @ markdown.js:7
> c @ markdown.js:7
> Promise.then
> init @ markdown.js:7
> s @ plugins.js:130
> (anonymous) @ plugins.js:146
> initPlugins @ plugins.js:98
> (anonymous) @ plugins.js:85
> load @ plugins.js:41
> initialize @ reveal.js:161
> (anonymous) @ index.js:38
> (anonymous) @ Test Vault for Advanced Slides.md:223
> img_b.jpg:1 
>         
>         
>        GET http://localhost:3011/images/img_b.jpg 404 (Not Found)
> Image
> (anonymous) @ markdown.js:7
> c @ markdown.js:7
> Promise.then
> init @ markdown.js:7
> s @ plugins.js:130
> (anonymous) @ plugins.js:146
> initPlugins @ plugins.js:98
> (anonymous) @ plugins.js:85
> load @ plugins.js:41
> initialize @ reveal.js:161
> (anonymous) @ index.js:38
> (anonymous) @ Test Vault for Advanced Slides.md:223

best regards,
AM

### Expected Behavior

- Image show up in obsidian preview
- Images show up in browser

### Current behaviour

- Image dont show up in obsidian preview
- Images dont show up in browser

### Steps to reproduce

1. Embed images in obsidian in a slides note 
2. Start slides server
3. Check out preview
4. Check out browser

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [x] Windows

### Obsidian Version

1.8.4

### Slides Extended Plugin Version

2.1.8

### Checks

- [x] I have tried it in the sandbox vault with only this plugin enabled

**Comment by 4Kp3n** [comment]
Hi,
same issue here.
Obsidian version 1.8.4, Slides Extended plugin version 2.1.8

Using Windows 11 Pro with Build 22631.

Is there something I can do to help investigate this?

Really missing the plugin atm.

**Comment by ebullient** [comment]
It's weird because I can't reproduce it here... at all.

**Comment by 4Kp3n** [comment]
Is there a way I can assist?

I actually have a second vault where the feature works but I'm unsure why.
The main difference is that the vault files reside on a Google drive.

I can't reproduce it/make it work in a newly created vault though.
Tested it also with a clean Windows 11 VM and a new Obsidian installation.

**Comment by ebullient** [comment]
Ok. so you can't reproduce it either, unless the have files are on a google drive?

I'm not sure I can do anything about that. It could be a file system restriction imposed by the browser. It could be a path resolution problem because the files are resolved/loaded in a way that node doesn't expect.

I will eventually get here, but I think your workaround is to not work directly from google drive. That isn't ideal if that is your sync mechanism, but I have no idea how I would try to account for a google drive mount, given I'm within electron using either standard Obsidian or node file loading mechanisms. I'm not doing anything esoteric or custom.

**Comment by 4Kp3n** [comment]
No the other way around.
I can't make the plugin work in a fresh/clean environment.

Windows 11 Enterprise
10.0.26100

Obsidian 1.8.7

**Comment by Swissbite** [comment]
So, I just opened Obsidian on my Windows System (Windows 11, Obsidian 1.8.9) and it does not work for my case

To re-create the behavior:
- I'm storing all assets under the folder `_assets` in the root of the vault
- I'm linking to the assets - as any other Obsidian link - with simple the file name

On technical level: It generates the correct path in the resulting HTML, like `/_assets/Kotlin Full Color Logo Mark RGB.png`
But this content is not served on Windows

It's working on an Ubuntu derivate system. Same vault, same slides.

What I tried to reproduce the issue:

- Use the Sandbox Vault
- Install and activate Plugin
- Create the folder `_asset` and add any image there
- Create a simple slide which references the image

Result: Same behavior, it will not show the image.

- Does sanitize the file name helps? (no spaces, no special characters): No
- Does moving the file next to the slide help? No
- Does explizit path reference help? No

**Comment by ebullient** [comment]
And this is just windows, which I don't have and can't test. 

I did just find that I was masking actual errors as 404. I've just pushed a release with that change along with some better logs for the resolved paths. Can y'all try again so we can see what is actually happening?

**Comment by danraymond** [comment]
Hello, Just helping to shed some light on this issue.  My Advanced slides that are local and refer to backgrounds stored in my vault do not display recently, They do however show up in the browser preview. I traced the error to the fact that Obsidian no longer allows internal references to local images as a source! It has affected many of my vault files. It does not effect normal  [[myimage.png]] references but in code where you would use a URL reference such as src="blah blah" you must use an online image fully formed URL such as "http://unsplash.com/mylovelyimage.png. So its not to do with the slide plugin code itself

**Comment by ebullient** [comment]
AH. yes. if you use <img src="" ../> directly, that has problems.

I handle both wikilinks and markdown links to make them proper resources (with the access policy that Obsidian allows). I always use markdown links, which is why I didn't see it.

**Comment by JosephBrooksbank** [comment]
The issue is still happening for me. 

- Obsidian v1.8.10
- slides extended v2.1.13
- Windows 11 (Pro)

Just for this I got Catalyst to see if Obsidian v1.9.2 would help. Unfortunately not. Tried wikilink and standard markdown syntax. Getting that 404:

```
http://localhost:3000/my_image.png 404 (Not Found) 
```

If I revert to Advanced Slides, it works fine and I get a 200/304 for `http://localhost:3000/my_image.png`. I can look into this more on my own this afternoon but first I need to actually write the slides I need for my presentation later today 😅
